### ISSUE TITLE
Font Crashes MathIsland.Activity

### ISSUE THREAD

**Issue by liam-middlebrook** [liam-middlebrook/math-island#22]
```
Initializing MathIsland
Traceback (most recent call last):
  File "/usr/bin/sugar-activity", line 161, in <module>
    main()
  File "/usr/bin/sugar-activity", line 156, in main
    instance = create_activity_instance(activity_constructor, activity_handle)
  File "/usr/bin/sugar-acitvity", line 42, in create_activity_instance
    activity = constructor(handle)
  File "/home/olpc/Activities/MathIsland.activity/MathIslandActivity.py" line 26, in __init__
    self.game = MathIsland.MathIsland()
  File "/home/olpc/Activities/MathIsland.activity/MathIsland.py", line 23, in __init__
    self.font_obj = pygame.font.Font('content/fonts/DroidSans.ttf', 32)
pygame.eror: font not initialized
Exited with status 1, pid 1725 data (None, <open file '<fdopen>', mode 'w' at 0x91d50d0>, '44126d11c76ead23fe36cd6ad09b906c2f1bc511')
```

Please include the proper font file so `sudo setup.py install` will properly function.

**Comment by cgonyeo** [comment]
Fixed this issue, game now correctly launches as an activity. A new issue has arisen though, in that when launched this way keyboard input is broken. Following issue was made to record this.
https://github.com/liam-middlebrook/math-island/issues/25
